Dev
denisafilip/food-ordering pull request #1
Opened 2019-10-30 20:47 UTC by denisafilip

2019-10-30 22:16 UTC, Ranapop requested changes
See code comments +
![image](https://user-images.githubusercontent.com/11149213/67903181-9a4c1900-fb73-11e9-9246-a5e6a771ef51.png)

2019-10-30 22:16 UTC, Ranapop commented on main.c
> +                //scanf("%s", additionalInfo);
do not leave code commented out

2019-10-30 22:16 UTC, Ranapop commented on main.c
> +                while((c= getchar()) != '\n' && c != EOF);*/
same here: don't leave code commented out

2019-11-02 19:05 UTC, merged

2019-11-04 05:58 UTC, denisafilip commented
Bună ziua! Nu sunt tocmai lămurită, am primit 10 pe assignmentul cu food-ordering? 


> On 2 Nov 2019, at 21:05, Ranapop <notifications@github.com> wrote:
> 
> ﻿
> Merged #1 into master.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-04 21:01 UTC, Ranapop commented
da, puteai scrie mail :)